name: Daily Market Update

on:
  schedule:
    # Run at 9:30 AM IST (4:00 AM UTC) on weekdays
    - cron: '0 4 * * 1-5'
  workflow_dispatch:  # Allow manual trigger

jobs:
  send_market_update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Clean Python environment
      run: |
        python -m pip uninstall -y pandas numpy yfinance
        rm -rf ~/.cache/pip
        
    - name: Install dependencies
      run: |
        python -m pip install --no-cache-dir --upgrade pip
        python -m pip install --no-cache-dir -r requirements.txt
        
    - name: Run market analysis script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        # Print Python version and installed packages
        python --version
        pip list
        
        # Run script with detailed error output
        python -u market_analysis.py 2>&1
        
    - name: Debug on failure
      if: failure()
      run: |
        echo "Checking environment variables (safely):"
        echo "TELEGRAM_BOT_TOKEN exists: ${{ secrets.TELEGRAM_BOT_TOKEN != '' }}"
        echo "TELEGRAM_CHAT_ID exists: ${{ secrets.TELEGRAM_CHAT_ID != '' }}" 
