name: Daily Market Update

on:
  schedule:
    # Run at 9:30 AM IST (4:00 AM UTC) on weekdays
    - cron: '0 4 * * 1-5'
  workflow_dispatch:  # Allow manual trigger

jobs:
  send_market_update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run market analysis script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python market_analysis.py 
